### ISSUE TITLE
could you release the finetune performance with fewer epoch on glue?

### ISSUE THREAD

**Issue by RyanHuangNLP** [microsoft/MPNet#1]
could you release the finetune performance with fewer epoch on glue, such as epoch 3 the same as bert or roberta?

**Comment by StillKeepTry** [comment]
Using Roberta hyper-parameter to fine-tune the released checkpoint can achieve:

MNLI | QNLI | QQP | RTE | SST-2 | MRPC | CoLA | STS-B
---|---|---|---|---|---|---|---
86.9 | 92.6 | 91.6 | 85.4 | 94.4 | 89.3 | 60.5 | 89.7 

We will update the results when our training is finished.
