### ISSUE TITLE
The exact English pretraining data and Chinese pretraining data that are exact same to the BERT paper's pretraining data. 

### ISSUE THREAD

**Issue by guotong1988** [microsoft/MPNet#12]
Any one know where to get them?
Thank you and thank you.

**Comment by StillKeepTry** [comment]
Generally, we need to crawl Wikipedia + bookcorpus by myself. The below are some scripts for crawling: 

[https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT/data/create_datasets_from_start.sh](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT/data/create_datasets_from_start.sh)
