### ISSUE TITLE
input mode questions?

### ISSUE THREAD

**Issue by RyanHuangNLP** [microsoft/MPNet#2]
is it input mode use `mlm` is like roberta, and use `plm` is like xlnet?

and by the way, would you provide the script to convert the model format to the huggingface transformers ones?

**Comment by StillKeepTry** [comment]
@RyanHuangNLP Yes, our code integrates `mlm` and 'plm' at the same time. Besides, we are preparing the models, code, and documents for huggingface version. Please wait.
