### ISSUE TITLE
Access to the released fairseq checkpoint

### ISSUE THREAD

**Issue by GeorgeSanchezTR** [microsoft/MPNet#20]
Hi I would like access the released fairseq checkpoint model - to continue pretraining on it
https://modelrelease.blob.core.windows.net/pre-training/MPNet/mpnet.base.tar.gz
This URL is not accessible to the public

**Comment by StillKeepTry** [comment]
Can you utilize Hugging Face version?  Please see https://huggingface.co/microsoft/mpnet-base

**Comment by GeorgeSanchezTR** [comment]
@StillKeepTry 
I have modified the fairseq code for some additional losses. The mpnet pretraining code for permutation is not huggingface right?
Is there a way to convert the huggingface to fairseq? to load it as --restore-file using fairseq-train

This issue is the same - https://github.com/microsoft/MPNet/issues/11

**Comment by StillKeepTry** [comment]
@GeorgeSanchezTR I have uploaded a fairseq version at [here](https://huggingface.co/KaitaoSong/MPNet/tree/main).

**Comment by GeorgeSanchezTR** [comment]
@StillKeepTry Thank you very much!
I will take a look.
