### ISSUE TITLE
关于SQuAD 2.0的评估

### ISSUE THREAD

**Issue by PROoshio** [microsoft/MPNet#3]
请问，论文中SQuAD2.0的dev结果是采用默认阈值0 （是否有答案），还是best f1和best em呢? 非常感谢～

**Comment by StillKeepTry** [comment]
We report best f1 & best em, according to the setting of huggingface.

**Comment by PROoshio** [comment]
感谢回复，但是我看代码中使用的是默认阈值 => null_score_diff_threshold=0.0
https://github.com/microsoft/MPNet/blob/e4b4cd841b309a4a85249a49c93bf6c6c30b0c1c/pretraining/fairseq/tasks/squad2.py
![图片](https://user-images.githubusercontent.com/35445537/87515929-2de85a00-c6af-11ea-8843-6c9db620c5fe.png)
评估时，并没有像BERT和XLNET那样根据dev集合选择最优的阈值，并输出best f1和best em(下图绿框)
![图片](https://user-images.githubusercontent.com/35445537/87516280-b7982780-c6af-11ea-9df9-3ad5a57b3a76.png)
请问MPNet中的dev集合结果是红色框输出还是绿色呢？

**Comment by StillKeepTry** [comment]
We report results in the green box. Besides, this squad function in fairseq version is not perfect enough. In this version, we need to test every checkpoint to report best f1 & em. We are preparing a hugging face version, which will support more functions for squad evaluation.

**Comment by PROoshio** [comment]
好的！我怕没有描述清楚，再冒昧地确认下：在每个checkpoint，先根据初始阈值(null_score_diff_threshold=0.0)得到best_f1_thresh，之后设置(null_score_diff_threshold=best_f1_thresh)输出论文中的dev结果：best_f1。对吧，非常感谢🙏

**Comment by StillKeepTry** [comment]
Yes

**Comment by PROoshio** [comment]
非常感谢～
