### ISSUE TITLE
MPNet如何训练长序列分类任务IMDB和RACE呢？

### ISSUE THREAD

**Issue by PROoshio** [microsoft/MPNet#4]
是否采用[:128] + [382:]这种截断方式么？感谢～

**Comment by StillKeepTry** [comment]
RACE的训练细节和[Roberta](https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.race.md)类似
IMDB也和[RoBERTa](https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.custom_classification.md)一致
