### ISSUE TITLE
可否圈下重点代码部分，fairseq代码太多

### ISSUE THREAD

**Issue by guotong1988** [microsoft/MPNet#6]
多谢多谢！
@tobyoup @StillKeepTry

**Comment by StillKeepTry** [comment]
主要是这么几个文件：

- https://github.com/microsoft/MPNet/blob/master/pretraining/fairseq/tasks/masked_permutation_lm.py
- https://github.com/microsoft/MPNet/blob/master/pretraining/fairseq/models/masked_permutation_net.py

其他如相对编码，微调则在https://github.com/microsoft/MPNet/blob/master/pretraining/fairseq/modules/transformer_sentence_encoder.py 等文件
