### ISSUE TITLE
关于MPNet在GLUE dev集合上结果的疑问？

### ISSUE THREAD

**Issue by PROoshio** [microsoft/MPNet#7]
恭喜MPNet被NIPS2020接收，在最新一版的MPNet论文中，请问GLUE的dev集合中RTE和MRPC以及STS-B这几个任务有没有用MNLI checkpoint热启动呢？感谢～

**Comment by StillKeepTry** [comment]
RTE，MRPC和STS-B用了MNLI做初始化，与roberta一致
