### ISSUE TITLE
would you release the code about convert the mpnet to the transformers one?

### ISSUE THREAD

**Issue by RyanHuangNLP** [microsoft/MPNet#8]
would you release the code about convert the mpnet to the transformers "microsoft/mpnet-base"?
I want to convert my pretrain one to the transformers format

**Comment by StillKeepTry** [comment]
This [file](https://gist.github.com/StillKeepTry/edb25fcc5a5cdcb4c46f38283164ef90) maybe ok

**Comment by ghost** [comment]
Hate to reopen this issue, but using the above file, I'm getting an error on line 67 that `'decoder.sentence_encoder.relative_attention_bias.weight'` doesn't exist in the original state dict. If I comment out this line, everything else is fine. Any idea if the name in the state dict has changed? Is it okay to ignore this when converting the model?

**Comment by ghost** [comment]
Never mind here, I realized I was using `mpnet_base` and not `mpnet_rel_base`
