### ISSUE TITLE
Training on SQUAD2 gives less results on Evaluation set (Research Paper shows better results)

### ISSUE THREAD

**Issue by bhadreshpsavani** [microsoft/MPNet#9]
I tried Training [MPNet ](https://modelrelease.blob.core.windows.net/pre-training/MPNet/mpnet.base.tar.gz) on SQUAD2 data below is the result I was getting on Evalutionset

I used this [script](https://github.com/microsoft/MPNet/blob/master/MPNet/README.squad.md) 

```
(exact, 50.07159100480081)                                                                                  
(f1, 50.07159100480081)
(total, 11873)
(HasAns_exact, 0.0)
(HasAns_f1, 0.0)
(HasAns_total, 5928)
(NoAns_exact, 100.0)
(NoAns_f1, 100.0)
(NoAns_total, 5945)
(best_exact, 50.07159100480081)
(best_exact_thresh, 0.0)
(best_f1, 50.07159100480081)
(best_f1_thresh, 0.0)
```

**Comment by StillKeepTry** [comment]
We recommend you to use [huggingface version](https://github.com/StillKeepTry/transformers/blob/master/src/transformers/modeling_mpnet.py) for squad fine-tuning.
